services:

  fe:
    depends_on:
      - be
    image : ${PROJECT}-fe:${TAG}
    ports:
      - 127.0.0.1:${WEB_PORT}:80
    restart: unless-stopped

  be:
    image : ${PROJECT}-be:${TAG}
    restart: unless-stopped

